create table public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  email text not null check (char_length(email) between 3 and 254),
  message text not null check (char_length(message) between 1 and 5000),
  created_at timestamptz not null default now()
);

alter table public.contact_submissions enable row level security;
revoke all on public.contact_submissions from anon, authenticated;
grant all on public.contact_submissions to service_role;